spring:
  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          import_files: classpath:db/data.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        connection:
          charSet: UTF-8
        format_sql: true
#        show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: hjr-bucket
    credentials:
      access-key: AKIA3XBXJOXXC2SZ63GV
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false